name: Frontend CI

on:
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'vite.config.*'
      - '.github/workflows/frontend-ci.yml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 3) Dependencies installieren (CI-äquivalent)
      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint + Format check
        run: pnpm run lint -- --max-warnings=0

      - name: Type-check (vue-tsc)
        run: pnpm run type-check

      - name: Unit tests (Vitest)
        run: pnpm run test:unit -- --coverage

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: E2E tests (Playwright)
        run: pnpm run test:e2e
